"""Core domain modules for the Idiot Index application."""

from .analytics import (
    HealthAggregate,
    HealthBand,
    HealthBandBreakdown,
    HealthRisk,
    HealthScoreConfig,
    HealthSummary,
    compute_health_scores,
    summarise_health,
)
from .cache import Cache, CacheStats, get_api_cache, get_computation_cache
from .config import (
    AppConfig,
    CacheConfig,
    ConfigError,
    ConfigValidationResult,
    DistributedRateLimitConfig,
    Environment,
    RateLimitConfig,
    SnapshotRemoteStorageConfig,
    get_config_summary,
    load_config,
    validate_config,
)
from .metrics import MetricConfig, compute_metrics, format_for_display
from .normalize import (
    DEFAULT_COLUMN_ALIASES,
    NormalizationOptions,
    apply_dtype_overrides,
    normalize_columns,
)
from .public_data import (
    AUTH_NONE,
    DEFAULT_CLEANING_VERSION,
    DEFAULT_PUBLIC_DATASETS,
    DEFAULT_SCHEMA_VERSION,
    DIRECT_INDUSTRY_FIELD_MAPPINGS,
    DIRECT_INDUSTRY_SCHEMA,
    IMPLEMENTATION_STAGES,
    SIGNAL_FIELD_MAPPINGS,
    SIGNAL_SCHEMA,
    CatalogValidationError,
    DatasetDefinition,
    EraWindow,
    FetchDecision,
    ImplementationStatus,
    ManifestError,
    ManifestStore,
    ReleaseIdentity,
    ReleaseManifest,
    build_release_manifest,
    hash_payload,
    public_dataset_catalog,
    split_periods_into_eras,
    validate_dataset_catalog,
)
from .security import FilePolicy, SecurityUtils
from .types import ValidationResult
from .utils import (
    HTTPRequestError,
    InvalidJSONError,
    RetryEvent,
    RetryPolicy,
    register_retry_observer,
    safe_get_json,
)

__all__ = [
    "AUTH_NONE",
    "AppConfig",
    "Cache",
    "CatalogValidationError",
    "HealthAggregate",
    "HealthBand",
    "HealthBandBreakdown",
    "HealthRisk",
    "HealthScoreConfig",
    "HealthSummary",
    "CacheConfig",
    "CacheStats",
    "ConfigError",
    "ConfigValidationResult",
    "DEFAULT_COLUMN_ALIASES",
    "DEFAULT_CLEANING_VERSION",
    "DEFAULT_PUBLIC_DATASETS",
    "DEFAULT_SCHEMA_VERSION",
    "DIRECT_INDUSTRY_SCHEMA",
    "DIRECT_INDUSTRY_FIELD_MAPPINGS",
    "DatasetDefinition",
    "NormalizationOptions",
    "EraWindow",
    "apply_dtype_overrides",
    "DistributedRateLimitConfig",
    "Environment",
    "FetchDecision",
    "FilePolicy",
    "HTTPRequestError",
    "IMPLEMENTATION_STAGES",
    "InvalidJSONError",
    "ImplementationStatus",
    "ManifestError",
    "ManifestStore",
    "MetricConfig",
    "RetryEvent",
    "RateLimitConfig",
    "ReleaseIdentity",
    "ReleaseManifest",
    "SnapshotRemoteStorageConfig",
    "RetryPolicy",
    "SIGNAL_SCHEMA",
    "SIGNAL_FIELD_MAPPINGS",
    "build_release_manifest",
    "register_retry_observer",
    "SecurityUtils",
    "ValidationResult",
    "compute_health_scores",
    "compute_metrics",
    "format_for_display",
    "get_api_cache",
    "get_computation_cache",
    "get_config_summary",
    "hash_payload",
    "load_config",
    "normalize_columns",
    "public_dataset_catalog",
    "safe_get_json",
    "split_periods_into_eras",
    "summarise_health",
    "validate_dataset_catalog",
    "validate_config",
]
